//
// Created by ludwig on 2/22/25.
//

#ifndef TEST_DONKOSSTATUSCODE_H
#define TEST_DONKOSSTATUSCODE_H

typedef enum DonkosStatusCodes_
{
    OKAY,
    ADC_INIT_FAILED,
    ADC_CONFIG_FAILED,
    ADC_START_FAILED,
    ADC_POLL_FOR_CONVERSION_FAILED,
    ADC_GET_VALUE_FAILED,
    ADC_STOP_FAILED,
    TIM_INIT_FAILED,
    TIM_CONFIG_CLOCK_FAILED,
    TIM_MASTER_CONFIG_SYNC_FAILED,
    TIM_START_FAILED,
    TIM_PWM_INIT_FAILED,
    TIM_PWM_CONFIG_CHANNEL_FAILED,
    TIM_PWM_START_FAILED,
    TIM_PWM_STOP_FAILED,
    TIM_BREAK_DEAD_CONFIG_FAILED,
    I2C_INIT_FAILED,
    I2C_CONFIG_ANALOG_FILTER_FAILED,
    I2C_CONFIG_DIGITAL_FILTER_FAILED,
    SSD_DISPLAY_INIT_FAILED,
    SPI_INIT_FAILED,
    SPI_TRANSMIT_FAILED,
    APPLICATION_ERROR = 99
} DonkosStatusCodes;


#endif //TEST_DONKOSSTATUSCODE_H
