#ifndef DONKOS_ATRESPONSECODE_H
#define DONKOS_ATRESPONSECODE_H

constexpr const char* ATResponseStringMap[] = {
    "Okay",
    "UART_RingBufferFull",
    "UART_CommunicationInitFailed",
    "CIFSR_TransmitFailed",
    "CIFSR_TimeoutWaitingForOkay",
    "CIFSR_UnexpectedResponse",
    "GMR_TransmitFailed",
    "GMR_TimeoutWaitingForOkay",
    "GMR_UnexpectedResponse",
    "GMR_BufferInsufficientForData",
    "RST_TransmitFailed",
    "CWMODE_TransmitFailed",
    "CWMODE_TimeoutWaitingForOkay",
    "CIPMUX_TransmitFailed",
    "CIPMUX_TimeoutWaitingForOkay",
    "CWJAP_BufferInsufficientForSettings",
    "CWJAP_TransmitFailed",
    "CWJAP_CouldNotConnectToAccessPoint",
    "CIPDNS_TransmitFailed",
    "CIPDNS_TimeoutWaitingForOkay",
    "CIPSTART_TransmitFailed",
    "CIPSTART_TimeoutWaitingForOkay",
    "CIPSEND_TransmitFailed",
    "CIPSEND_TimeoutWaitingForByteStart",
    "GET_REQUEST_BufferInsufficientForHostAndPath",
    "GET_REQUEST_TransmitFailed",
    "GET_REQUEST_TimeoutWaitingForConnectionClose",
    "GET_REQUEST_InvalidResponse",
    "GET_REQUEST_ResponseBufferInsufficient",
    "CIPSNTP_TransmitFailed",
    "CIPSNTP_TimeoutWaitingForOkay",
    "CIPSSLSIZE_TransmitFailed",
    "CIPSSLSIZE_TimeoutWaitingForOkay",
};

enum class ATResponseCode {
    Okay,
    UART_RingBufferFull,
    UART_CommunicationInitFailed,
    CIFSR_TransmitFailed,
    CIFSR_TimeoutWaitingForOkay,
    CIFSR_UnexpectedResponse,
    GMR_TransmitFailed,
    GMR_TimeoutWaitingForOkay,
    GMR_UnexpectedResponse,
    GMR_BufferInsufficientForData,
    RST_TransmitFailed,
    CWMODE_TransmitFailed,
    CWMODE_TimeoutWaitingForOkay,
    CIPMUX_TransmitFailed,
    CIPMUX_TimeoutWaitingForOkay,
    CWJAP_BufferInsufficientForSettings,
    CWJAP_TransmitFailed,
    CWJAP_CouldNotConnectToAccessPoint,
    CIPDNS_TransmitFailed,
    CIPDNS_TimeoutWaitingForOkay,
    CIPSTART_TransmitFailed,
    CIPSTART_TimeoutWaitingForOkay,
    CIPSEND_TransmitFailed,
    CIPSEND_TimeoutWaitingForByteStart,
    GET_REQUEST_BufferInsufficientForHostAndPath,
    GET_REQUEST_TransmitFailed,
    GET_REQUEST_TimeoutWaitingForConnectionClose,
    GET_REQUEST_InvalidResponse,
    GET_REQUEST_ResponseBufferInsufficient,
    CIPSNTP_TransmitFailed,
    CIPSNTP_TimeoutWaitingForOkay,
    CIPSSLSIZE_TransmitFailed,
    CIPSSLSIZE_TimeoutWaitingForOkay,
};

const char *ATResponseCode_ToString(const ATResponseCode &code);

#endif //DONKOS_ATRESPONSECODE_H